import 'product.dart';

final List<Product> allProducts = [
  Product(
    id: 1,
    title: 'Wireless Noise-Cancelling Headphones',
    description: 'Over-ear Bluetooth headphones with active noise cancellation and 30 hours of battery life.',
    category: 'electronics',
    price: 4999,
    discountPercentage: 37.5,
    rating: 4.4,
    brand: 'SoundWave',
    warrantyInformation: '1 year warranty',
    shippingInformation: 'Ships in 1-2 business days',
    availabilityStatus: 'In Stock',
    images: [
      'https://picsum.photos/seed/headphones1/600/600',
      'https://picsum.photos/seed/headphones2/600/600',
    ],
    thumbnail: 'https://picsum.photos/seed/headphones1/300/300',
  ),
  Product(
    id: 2,
    title: 'Smart Fitness Watch',
    description: 'AMOLED smartwatch with heart-rate tracking, GPS and 7-day battery life.',
    category: 'electronics',
    price: 3499,
    discountPercentage: 41.7,
    rating: 4.2,
    brand: 'FitPulse',
    warrantyInformation: '1 year warranty',
    shippingInformation: 'Ships in 1-2 business days',
    availabilityStatus: 'In Stock',
    images: [
      'https://picsum.photos/seed/watch1/600/600',
      'https://picsum.photos/seed/watch2/600/600',
    ],
    thumbnail: 'https://picsum.photos/seed/watch1/300/300',
  ),
  Product(
    id: 3,
    title: 'Men\'s Cotton Casual Shirt',
    description: 'Breathable 100% cotton shirt with a regular fit and button-down collar.',
    category: 'fashion',
    price: 899,
    discountPercentage: 50.0,
    rating: 4.1,
    brand: 'UrbanThread',
    warrantyInformation: 'No warranty',
    shippingInformation: 'Ships in 2-3 business days',
    availabilityStatus: 'In Stock',
    images: [
      'https://picsum.photos/seed/shirt1/600/600',
      'https://picsum.photos/seed/shirt2/600/600',
    ],
    thumbnail: 'https://picsum.photos/seed/shirt1/300/300',
  ),
  Product(
    id: 4,
    title: 'Women\'s Running Shoes',
    description: 'Lightweight mesh running shoes with cushioned sole and anti-slip grip.',
    category: 'footwear',
    price: 1999,
    discountPercentage: 42.9,
    rating: 4.3,
    brand: 'StrideX',
    warrantyInformation: '6 months warranty',
    shippingInformation: 'Ships in 2-3 business days',
    availabilityStatus: 'In Stock',
    images: [
      'https://picsum.photos/seed/shoes1/600/600',
      'https://picsum.photos/seed/shoes2/600/600',
    ],
    thumbnail: 'https://picsum.photos/seed/shoes1/300/300',
  ),
  Product(
    id: 5,
    title: 'Insulated Steel Water Bottle 1L',
    description: 'Vacuum insulated bottle that keeps drinks cold for 24 hours and hot for 12.',
    category: 'home-kitchen',
    price: 549,
    discountPercentage: 45.0,
    rating: 4.5,
    brand: 'HydroKeep',
    warrantyInformation: '1 year warranty',
    shippingInformation: 'Ships in 1-2 business days',
    availabilityStatus: 'In Stock',
    images: ['https://picsum.photos/seed/bottle1/600/600'],
    thumbnail: 'https://picsum.photos/seed/bottle1/300/300',
  ),
  Product(
    id: 6,
    title: 'Ergonomic Office Chair',
    description:
        'High-back mesh chair with adjustable lumbar support and armrests.',
    category: 'furniture',
    price: 7499,
    discountPercentage: 42.3,
    rating: 4.0,
    brand: 'ComfyDesk',
    warrantyInformation: '2 years warranty',
    shippingInformation: 'Ships in 4-5 business days',
    availabilityStatus: 'Low Stock',
    images: [
      'https://picsum.photos/seed/chair1/600/600',
      'https://picsum.photos/seed/chair2/600/600',
    ],
    thumbnail: 'https://picsum.photos/seed/chair1/300/300',
  ),
  Product(
    id: 7,
    title: 'Bluetooth Portable Speaker',
    description:
        '20W waterproof speaker with 360° sound and 12 hours of playtime.',
    category: 'electronics',
    price: 2299,
    discountPercentage: 42.5,
    rating: 4.3,
    brand: 'SoundWave',
    warrantyInformation: '1 year warranty',
    shippingInformation: 'Ships in 1-2 business days',
    availabilityStatus: 'In Stock',
    images: [
      'https://picsum.photos/seed/speaker1/600/600',
      'https://picsum.photos/seed/speaker2/600/600',
    ],
    thumbnail: 'https://picsum.photos/seed/speaker1/300/300',
  ),
  Product(
    id: 8,
    title: 'Laptop Backpack 30L',
    description: 'Water-resistant backpack with padded laptop compartment and USB charging port.',
    category: 'bags',
    price: 1299,
    discountPercentage: 48.0,
    rating: 4.4,
    brand: 'TrekPro',
    warrantyInformation: '6 months warranty',
    shippingInformation: 'Ships in 2-3 business days',
    availabilityStatus: 'In Stock',
    images: [
      'https://picsum.photos/seed/backpack1/600/600',
      'https://picsum.photos/seed/backpack2/600/600',
    ],
    thumbnail: 'https://picsum.photos/seed/backpack1/300/300',
  ),
  Product(
    id: 9,
    title: 'Yoga Mat 6mm',
    description:
        'Non-slip, cushioned yoga mat with a carry strap for easy transport.',
    category: 'sports',
    price: 699,
    discountPercentage: 46.2,
    rating: 4.2,
    brand: 'FlexFit',
    warrantyInformation: 'No warranty',
    shippingInformation: 'Ships in 1-2 business days',
    availabilityStatus: 'In Stock',
    images: ['https://picsum.photos/seed/yogamat1/600/600'],
    thumbnail: 'https://picsum.photos/seed/yogamat1/300/300',
  ),
  Product(
    id: 10,
    title: 'Non-Stick Cookware Set',
    description: 'Induction-friendly 3-piece set with PFOA-free coating and stay-cool handles.',
    category: 'home-kitchen',
    price: 2499,
    discountPercentage: 44.5,
    rating: 4.1,
    brand: 'ChefMate',
    warrantyInformation: '1 year warranty',
    shippingInformation: 'Ships in 3-4 business days',
    availabilityStatus: 'Out of Stock',
    images: [
      'https://picsum.photos/seed/cookware1/600/600',
      'https://picsum.photos/seed/cookware2/600/600',
    ],
    thumbnail: 'https://picsum.photos/seed/cookware1/300/300',
  ),
];
